vinlla_admin:
    resource: "@VinllaLandingBundle/Resources/config/routing_admin.yml"
    prefix:   /admin

vinlla_secured:
     resource: "@VinllaLandingBundle/Resources/config/routing_login.yml"
     prefix:   /secured

VinllaLandingBundle_homepage:
    pattern:  /
    defaults: { _controller: VinllaLandingBundle:Default:index }
    requirements:
        _method:  GET

VinllaLandingBundle_feature:
    pattern:  /fitur/{id}.html
    defaults: { _controller: VinllaLandingBundle:Default:feature }
    requirements:
        _method:  GET
        id: \d+

VinllaLandingBundle_download:
    pattern:  /unduh-vinlla.html
    defaults: { _controller: VinllaLandingBundle:Default:download }
    requirements:
        _method:  GET

