parameters:
#    vinlla_landing.example.class: Vinlla\LandingBundle\Example

services:
#    vinlla_landing.example:
#        class: %vinlla_landing.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
