parameters:
#    vinlla_blog.example.class: Vinlla\BlogBundle\Example

services:
#    vinlla_blog.example:
#        class: %vinlla_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
